# TODO This resource should be created condidionally based on the provider or only the part of the provider should be created conditionally
---
{{- if .Values.aws_cluster_secret_store -}}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.aws_cluster_secret_store.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws_cluster_secret_store.region }}
      auth:
        {{ if .Values.aws_cluster_secret_store.use_iam_role }}
        jwt:
          serviceAccountRef:
            name: {{ .Release.Name }}-external-secrets
            namespace: {{ .Release.Namespace }}
        {{ end -}}
        {{ if .Values.aws_cluster_secret_store.use_iam_access_key }}
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Release.Name }}-aws-secrets-manager-credentials
            key: access-key
            namespace: {{ .Release.Namespace }}
          secretAccessKeySecretRef:
            name: {{ .Release.Name }}-aws-secrets-manager-credentials
            key: secret-key
            namespace: {{ .Release.Namespace }}
        {{ end }}
{{- end -}}
